In [4]:
import json
import pandas as pd
import re

In [2]:
df = pd.read_json('tmobile_detailed_specs.json')
df.head()

,url,title,specs,status
0,https://www.t-mobile.com/cell-phone/google-pix...,Customize your device,{'section_0': 'Phones / Google / Pixel 11 Pro ...,success
1,https://www.t-mobile.com/cell-phone/google-pix...,Customize your device,{'section_0': 'Phones / Google / Pixel 11 Pro ...,success
2,https://www.t-mobile.com/cell-phone/google-pix...,Customize your device,{'section_0': 'Phones / Google / Pixel 11 Goog...,success
3,https://www.t-mobile.com/cell-phone/google-pix...,Customize your device,{'section_0': 'Phones / Google / Pixel 11 Pro ...,success
4,https://www.t-mobile.com/cell-phone/samsung-ga...,Customize your device,{'section_0': 'Phones / Samsung / Galaxy Z Fol...,success

In [8]:
df['features'] = df['specs'].apply(lambda t: re.split(r'\bQuick Facts\b', str(t['section_77']))[0] )
df['product'] = df['url'].apply(lambda t: t.split('/')[-1])
df.head()

,url,title,specs,status,features,product
0,https://www.t-mobile.com/cell-phone/google-pix...,Customize your device,{'section_0': 'Phones / Google / Pixel 11 Pro ...,success,Specs\nKey features\n\nT-Satellite with Starli...,google-pixel-11-pro-xl
1,https://www.t-mobile.com/cell-phone/google-pix...,Customize your device,{'section_0': 'Phones / Google / Pixel 11 Pro ...,success,Specs\nKey features\n\nT-Satellite with Starli...,google-pixel-11-pro
2,https://www.t-mobile.com/cell-phone/google-pix...,Customize your device,{'section_0': 'Phones / Google / Pixel 11 Goog...,success,Specs\nKey features\n\nT-Satellite with Starli...,google-pixel-11
3,https://www.t-mobile.com/cell-phone/google-pix...,Customize your device,{'section_0': 'Phones / Google / Pixel 11 Pro ...,success,Specs\nKey features\n\nT-Satellite with Starli...,google-pixel-11-pro-fold
4,https://www.t-mobile.com/cell-phone/samsung-ga...,Customize your device,{'section_0': 'Phones / Samsung / Galaxy Z Fol...,success,Overview\nSpecs\nKey features\n\nT-Satellite w...,samsung-galaxy-z-fold8

In [9]:
df[['product','features']].to_csv('tmobile_detailed_specs.csv',index=False)